// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// extractT
NumericVector extractT(IntegerVector xs, IntegerVector ys, NumericMatrix ts);
RcppExport SEXP _bidag2_extractT(SEXP xsSEXP, SEXP ysSEXP, SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ts(tsSEXP);
    rcpp_result_gen = Rcpp::wrap(extractT(xs, ys, ts));
    return rcpp_result_gen;
END_RCPP
}
// collectC
NumericVector collectC(IntegerVector xs, NumericVector ys, int n);
RcppExport SEXP _bidag2_collectC(SEXP xsSEXP, SEXP ysSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(collectC(xs, ys, n));
    return rcpp_result_gen;
END_RCPP
}
// collectCcatwt
NumericMatrix collectCcatwt(IntegerVector xs, IntegerVector ys, NumericVector ws, int n, int m);
RcppExport SEXP _bidag2_collectCcatwt(SEXP xsSEXP, SEXP ysSEXP, SEXP wsSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ws(wsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(collectCcatwt(xs, ys, ws, n, m));
    return rcpp_result_gen;
END_RCPP
}
// collectCcat
IntegerMatrix collectCcat(IntegerVector xs, IntegerVector ys, int n, int m);
RcppExport SEXP _bidag2_collectCcat(SEXP xsSEXP, SEXP ysSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(collectCcat(xs, ys, n, m));
    return rcpp_result_gen;
END_RCPP
}
// takefirst
NumericVector takefirst(NumericVector xs, int pos);
RcppExport SEXP _bidag2_takefirst(SEXP xsSEXP, SEXP posSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< int >::type pos(posSEXP);
    rcpp_result_gen = Rcpp::wrap(takefirst(xs, pos));
    return rcpp_result_gen;
END_RCPP
}
// takelast
NumericVector takelast(NumericVector xs, int pos, int n);
RcppExport SEXP _bidag2_takelast(SEXP xsSEXP, SEXP posSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< int >::type pos(posSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(takelast(xs, pos, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bidag2_extractT", (DL_FUNC) &_bidag2_extractT, 3},
    {"_bidag2_collectC", (DL_FUNC) &_bidag2_collectC, 3},
    {"_bidag2_collectCcatwt", (DL_FUNC) &_bidag2_collectCcatwt, 5},
    {"_bidag2_collectCcat", (DL_FUNC) &_bidag2_collectCcat, 4},
    {"_bidag2_takefirst", (DL_FUNC) &_bidag2_takefirst, 2},
    {"_bidag2_takelast", (DL_FUNC) &_bidag2_takelast, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_bidag2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
