# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extractT <- function(xs, ys, ts) {
    .Call(`_bidag_extractT`, xs, ys, ts)
}

collectC <- function(xs, ys, n) {
    .Call(`_bidag_collectC`, xs, ys, n)
}

collectCcatwt <- function(xs, ys, ws, n, m) {
    .Call(`_bidag_collectCcatwt`, xs, ys, ws, n, m)
}

collectCcat <- function(xs, ys, n, m) {
    .Call(`_bidag_collectCcat`, xs, ys, n, m)
}

takefirst <- function(xs, pos) {
    .Call(`_bidag_takefirst`, xs, pos)
}

takelast <- function(xs, pos, n) {
    .Call(`_bidag_takelast`, xs, pos, n)
}

